### ISSUE TITLE
Installation of 0.0.8 failed due to server not opening on port 5005

### ISSUE THREAD

**Issue by szabgab** [Bailador/Bailador#205] opened 2017-07-15 07:49 UTC
```
# zef upgrade Bailador
===> Searching for: Bailador
===> Updating: Bailador:ver('0.0.8')
===> Testing: Bailador:ver('0.0.8')
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
0.0.0.0:5005 doesn't open in 60 sec.
  in sub wait-port at /root/.zef/store/Bailador-0.0.8.tar.gz/Bailador-0.0.8/t/lib/Helpers.pm6 (Helpers) line 19
  in block <unit> at t/20-cli.t line 181


    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 68
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2
===> Testing [FAIL]: Bailador:ver('0.0.8')
Use of Nil in string context
  in sub MAIN at /opt/rakudo-2017.06/install/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 253
Unexpected named argument '' passed
  in sub MAIN at /opt/rakudo-2017.06/install/share/perl6/site/sources/ED3033E8712BCF9F6DE53678B14A54705DF211A6 (Zef::CLI) line 253
  in block <unit> at /opt/rakudo-2017.06/install/share/perl6/site/resources/6182CA1C8C9C6ED5BBB3076B522103070B37DDA4 line 1

```

That test has some issues....

**Comment by ufobat** [comment] 2017-07-15 08:16
This seems to be a duplicate of #194.

As a workaround killall perl6 processes (esp those from previous installations)
`killall moar` and then `zef upgrade Bailador`

**Comment by szabgab** [comment] 2017-07-15 20:09
#194 has been fixed, but we still probably further improve t/20-cli.t to find a port that is not being used and use that for our tests instead of the current fixed ports that might be in use by other apps.

**Closed** 2017-08-01 08:06 UTC
