### ISSUE TITLE
Bailador app creation is broken.

### ISSUE THREAD

**Issue by cschwenz** [Bailador/Bailador#272] opened 2017-09-30 08:07 UTC
I cannot get `bailador` to create a new app.

From the fine documentation:
> At the command prompt, create a new Bailador application:
> $ bailador --name App-Name new

The result on my command line:
```
% bailador --name Asdf-Zxcv new
Usage:
  bailador [--name=<Str>] new
  bailador version
  bailador [-w=<Str>] [--config=<Str>] watch <app> -- Invokes your app on top of HTTP::Easy, reloads your app when changes are detected
  bailador [--config=<Str>] easy <app> -- Invokes your app on top of HTTP::Easy
  bailador [-t] [--config=<Str>] routes <app> -- Displays all the routes of your app
  bailador [--config=<Str>] ogre <app> -- Invokes your app on top of HTTP::Server::Ogre
  bailador [--config=<Str>] tiny <app> -- Invokes your app on top of HTTP::Server::Tiny
% bailador --name=Asdf-Zxcv new
--name=Project-Name is a required parameter
% bailador --name="Asdf-Zxcv" new
--name=Project-Name is a required parameter
% bailador --name=App-Name new
--name=Project-Name is a required parameter
% bailador --name=Project-Name new
--name=Project-Name is a required parameter
```

Bailador version:
```
% bailador version
Bailador 0.0.12
```

Perl6 version:
```
% perl6 -v
This is Rakudo version 2017.09-19-g9190a3b80 built on MoarVM version 2017.09.1
implementing Perl 6.c.
```

Zef version:
```
% zef info zef
- Identity: zef:ver<0.1.29>:auth<github:ugexe>
Source-url:	 git://github.com/ugexe/zef.git
```

OS:  MacOS 10.12.6

**Comment by ufobat** [comment] 2017-09-30 08:46
can you do a 'which bailador' please?

**Comment by cschwenz** [comment] 2017-09-30 19:07
Not sure why this will be helpful; as due to many reasons Perl6, and by extension Bailador, is installed to my home directory:
```
% which bailador
/Users/cal/local/share/perl6/site/bin/bailador
```

**Comment by ufobat** [comment] 2017-10-01 06:27
duplicate of #265 . will be fixed in next release

**Closed by ufobat** 2017-10-01 06:27 UTC
