### ISSUE TITLE
Installation failed due some failed tests

### ISSUE THREAD

**Issue by chsanch** [Bailador/Bailador#206] opened 2017-07-17 19:22 UTC
Hi,
I'm installing Bailador 0.0.8 in a fresh installation of Perl 6 on Mac with Rakudobrew:

```
$ perl6 --version
This is Rakudo version 2017.07 built on MoarVM version 2017.07
implementing Perl 6.c.
```
When I try to install Bailador with:

`$ zef install Bailador`

I got:

```
===> Testing: Bailador:ver('0.0.8')
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.

    # Failed test 'program terminated successfully'
    # at t/20-cli.t line 97
    # expected: '0'
    #      got: '1'

    # Failed test 'text matches 'rx:s/Result\: PASS/''
    # at t/20-cli.t line 100
    #      expected: 'rx:s/Result\: PASS/'
    #      got: ''
    # Looks like you failed 2 tests of 3

# Failed test 'test newly generated app with its test cases'
# at t/20-cli.t line 90
# Looks like you failed 1 test of 9

    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 68
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2

===> Testing [FAIL]: Bailador:ver('0.0.8')
```

Then I forced the installation with:

`$ zef install Bailador --force-test`

Bailador was installed, but I got another failed tests: 

```
===> Testing: Bailador:ver('0.0.8')
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.

    # Failed test 'program terminated successfully'
    # at t/20-cli.t line 97
    # expected: '0'
    #      got: '1'

    # Failed test 'text matches 'rx:s/Result\: PASS/''
    # at t/20-cli.t line 100
    #      expected: 'rx:s/Result\: PASS/'
    #      got: ''
    # Looks like you failed 2 tests of 3

# Failed test 'test newly generated app with its test cases'
# at t/20-cli.t line 90

    # Failed test 'text matches 'rx:s/\<h1\>Bailador App\<\/h1\>/''
    # at t/20-cli.t line 129
    #      expected: 'rx:s/\<h1\>Bailador App\<\/h1\>/'
    #      got: ''

    # Failed test 'text matches 'rx:s/Version 0\.0\.1/''
    # at t/20-cli.t line 130
    #      expected: 'rx:s/Version 0\.0\.1/'
    #      got: ''
    # Looks like you failed 2 tests of 2

# Failed test 'start app with bin/bailador watch'
# at t/20-cli.t line 109

    # Failed test 'text matches 'rx:s/\<h1\>Bailador App\<\/h1\>/''
    # at t/20-cli.t line 160
    #      expected: 'rx:s/\<h1\>Bailador App\<\/h1\>/'
    #      got: ''

    # Failed test 'text matches 'rx:s/Version 0\.0\.1/''
    # at t/20-cli.t line 161
    #      expected: 'rx:s/Version 0\.0\.1/'
    #      got: ''
    # Looks like you failed 2 tests of 2

# Failed test 'test app with watch command without bin directory'
# at t/20-cli.t line 138
# Looks like you failed 3 tests of 9

    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 68
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2

===> Testing [FAIL]: Bailador:ver('0.0.8')
Failed to get passing tests, but continuing with --force-test
```

**Comment by szabgab** [comment] 2017-07-17 19:38
It is probably because of this #194 that has been fixed after 0.0.8 was released.

Try the following to check if indeed this is the source of problem:

```
killall moar
zef test Bailador
```

**Comment by chsanch** [comment] 2017-07-17 20:15
I did this:
- Clone the repository
- Executed both commands you suggested
- I got this error:

```
===SORRY!===
Could not find Terminal::ANSIColor at line 3 in:
[ ... ]
```
- Installed Terminal::ANSIColor
- Executed again: `zef test Bailador`
- I got this:

```
$ zef test Bailador
===> Testing: Bailador:ver('0.0.8')
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.

    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 68
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2
===> Testing [OK] for Bailador:ver('0.0.8')
```

**Comment by szabgab** [comment] 2017-07-17 21:23
Thanks for checking. The last one is a pass. The failure you see is a todo test that Test or maybe prove6 should report as such or should not display at all.

**Comment by sed76** [comment] 2017-07-18 16:53
on my Mac

`perl --version `

says 

This is Rakudo version 2017.04.3 built on MoarVM version 2017.04-53-g66c6dda
implementing Perl 6.c.

After cloning repo, installing necessary modules and run 

`zef test Bailador
`
I've got

```
t/30-examples-app.t ...........4/15

    # Failed test 'route GET /hello/Foo.html'
    # at t/30-examples-app.t line 68
    # expected: $[200, [:Content-Type("text/html")], "Hello Foo.html!"]
    #      got: $[404, [:Content-Type("text/html;charset=UTF-8")], "<html>\n    <head>\n        <title>Custom 404 page</title>\n        <meta charset=\"UTF-8\">\n    </head>\n    <body>\n        <h1>Hello, this is 404 for you.</h1>\n    </body>\n</html>\n"]
    # Looks like you failed 1 test of 2
t/30-examples-app.t ........... ok
t/30-examples-echo.t .......... ok
t/30-examples-err.t ........... ok
t/30-examples-gradual.t ....... ok
t/30-examples-pastebin.t ...... ok
t/30-examples-postapp.t ....... ok
All tests successful.
Files=37, Tests=1248,  104 wallclock secs
Result: PASS
===> Testing [OK] for Bailador:ver('0.0.8')

```

So I was manage to install Bailador successfully.
```
All tests successful.
Files=37, Tests=1248,  117 wallclock secs
Result: PASS
===> Testing [OK] for Bailador:ver('0.0.8')
===> Installing: TAP::Harness:ver('0.0.2'):auth('Leon Timmermans')
 ===> Installing: Bailador:ver('0.0.8')

2 bin/ scripts [prove6 bailador] installed to:
/usr/local/Cellar/rakudo-star/2017.04/share/perl6/site/bin

```

Thank you. Installation process was unobvious for old Perl5 freak. =)

**Comment by szabgab** [comment] 2017-07-19 04:48
@sed76 you don't need to clone the repo to install Bailador. Only if you'd like to contribute to the project. Which you'd be welcome to!

**Comment by ufobat** [comment] 2017-08-01 07:15
this seems to be a duplicate of #224

**Closed by ufobat** 2017-08-01 07:15 UTC
