### ISSUE TITLE
Tests fails on Linux Mint 18.2 with rakudo 2017.10

### ISSUE THREAD

**Issue by isleofmax** [Bailador/Bailador#282] opened 2017-11-18 13:43 UTC
When I try to install Bailador with rakudo 2017.10 and zef version 0.1.30 on Linux Mint 18.2 I have theese errors:
```
===> Testing: Bailador:ver<0.0.14>
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# Skipping author test. Set AUTHOR_TESTING to enable.
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
# nothing to render, looks suspicious
# 
===> Testing [FAIL]: Bailador:ver<0.0.14>
Aborting due to test failure: Bailador:ver<0.0.14> (use --force-test to override)
  in code  at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 375
  in method test at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 353
  in code  at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 530
  in sub  at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 527
  in method install at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/29769DA546CA5B55E3D2F7F8C9D20095C41CCF61 (Zef::Client) line 633
  in sub MAIN at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/sources/3A2818F8A8CE2F1251F051B779AA0EC17DA2F72E (Zef::CLI) line 152
  in block <unit> at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/resources/91C74F08994E0006C3049614EF974F6E1A8EDF2D line 1
  in sub MAIN at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/bin/zef line 2
  in block <unit> at /home/massimo/rakudo-star-2017.10/install/share/perl6/site/bin/zef line 2
```

**Comment by ufobat** [comment] 2018-04-06 10:30
it might be a duplicate of #284

**Closed** 2018-04-14 13:04 UTC
