### ISSUE TITLE
Error in examples

### ISSUE THREAD

**Issue by JJ** [Bailador/Bailador#101] opened 2017-05-21 16:52 UTC
I'm getting this error as I run pretty much every example or program:
```
Entering the development dance floor: http://0.0.0.0:3000
Nothing given for new socket to connect or bind to
  in method connect at /home/jmerelo/.rakudobrew/moar-2017.04.3/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 33
  in method run at /home/jmerelo/.rakudobrew/moar-2017.04.3/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 49
  in sub baile at /home/jmerelo/.rakudobrew/moar-2017.04.3/install/share/perl6/site/sources/D57520A5A045A33D405E36DAA759641E90C1FD99 (Bailador) line 113
  in block <unit> at echo.pl6 line 23

Actually thrown at:
  in method run at /home/jmerelo/.rakudobrew/moar-2017.04.3/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 49
  in sub baile at /home/jmerelo/.rakudobrew/moar-2017.04.3/install/share/perl6/site/sources/D57520A5A045A33D405E36DAA759641E90C1FD99 (Bailador) line 113
  in block <unit> at echo.pl6 line 23
```
The port does not seem to be used. This was `echo.pl6`, BTW, but I'm getting the same error with other examples. Any idea?

**Comment by ufobat** [comment] 2017-05-21 17:57
it seems to work on my machine :-( which version of perl6 did you use? are your modules up to date? maybe this is related to the changes in IO.. i dont know, sorry

**Comment by JJ** [comment] 2017-05-21 18:01
It might. I'm using moar-2017.04.3, freshly installed.

**Comment by ufobat** [comment] 2017-05-21 18:11
i just switched to the current nom
```
┌─[martin@psyche] - [~/.workspace/p6/Bailador/examples] - [So Mai 21, 20:09]
└─[$] <git:(master*)> perl6 -v
This is Rakudo version 2017.05-16-g494659a built on MoarVM version 2017.05
implementing Perl 6.c.
┌─[martin@psyche] - [~/.workspace/p6/Bailador/examples] - [So Mai 21, 20:09]
└─[$] <git:(master*)> perl6 echo.pl6 
Entering the development dance floor: http://0.0.0.0:3000
[2017-05-21T18:09:46Z] Started HTTP server.
[2017-05-21T18:10:22Z] GET / HTTP/1.1
```

**Comment by JJ** [comment] 2017-05-22 05:41
Same error, from a fresh download of Perl6 and Bailador:
```
$ perl6 examples/echo.pl6
Entering the development dance floor: http://0.0.0.0:3000
Nothing given for new socket to connect or bind to
  in method connect at /home/jmerelo/.rakudobrew/moar-2017.05/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 33
  in method run at /home/jmerelo/.rakudobrew/moar-2017.05/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 49
  in sub baile at /tmp/Bailador/lib/Bailador.pm (Bailador) line 113
  in block <unit> at examples/echo.pl6 line 23

Actually thrown at:
  in method run at /home/jmerelo/.rakudobrew/moar-2017.05/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 49
  in sub baile at /tmp/Bailador/lib/Bailador.pm (Bailador) line 113
  in block <unit> at examples/echo.pl6 line 23
```
This is:

    Linux penny 3.13.0-34-generic #60-Ubuntu SMP Wed Aug 13 15:45:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JJ** [comment] 2017-05-22 17:17
It works without a glitch in my laptop, which is Ubuntu 16:04 and an older version of rakudobrew. Quite clearly the problem is upstream, but I can't figure out where it could be...

**Comment by zoffixznet** [comment] 2017-05-22 19:48
> Same error, from a fresh download of Perl6 and Bailador:

Fresh is how fresh? What's the version of the new download?

**Comment by zoffixznet** [comment] 2017-05-22 20:11
Can't repro the problem on 2017.04.3. I suspect it's your perms/firewall. Try changing host to localhost instead of 0.0.0.0 and it'll work, I bet.

(I'm also getting a bunch of test failures on 2017.05-15-g81221c5, but when I `look zef Bailador` and run the echo example it works)

**Comment by JJ** [comment] 2017-05-23 05:19
It does not. Same error with localhost and 127.0.0.1. And I have checked
https://github.com/supernovus/perl6-http-easy/blob/master/examples/test.p6
and it works fine. It does not work even if I use defaults in
HTTP::Easy::PSGI

**Comment by szabgab** [comment] 2017-06-21 08:34
Just wondering, have you tried `netcat -l 3000` and then browse to port 3000 ?

**Comment by JJ** [comment] 2017-06-21 08:41
don't think it will help, but will give it a try :-)

**Comment by szabgab** [comment] 2017-08-01 08:05
I think we can close this as we are not able to reproduce this and this only happened on a single machine.

**Closed by szabgab** 2017-08-01 08:05 UTC

**Comment by JJ** [comment] 2017-08-01 08:14
:+1:

**Comment by JJ** [comment] 2017-12-16 09:30
I am having this same problem again, and now I think I can pinpoint its origin. Here's the error:
```
Entering the dance floor: http://127.0.0.1:3000
Nothing given for new socket to connect or bind to. Invalid arguments to .new?
  in method connect at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 33
  in method run at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/100A1B43D02574570A9FA5343A0679EF35FBD229 (HTTP::Easy) line 49
  in method run at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/83CE580AD413E9CC8EEE0A7D52D47B98F511402C (Bailador::Command::easy) line 19
  in method baile at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/341F58F51C05C5B62B7CB9E146D9ECB7B2C07627 (Bailador::App) line 293
  in method baile at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/341F58F51C05C5B62B7CB9E146D9ECB7B2C07627 (Bailador::App) line 278
  in sub baile at /home/jmerelo/.rakudobrew/moar-2017.11/install/share/perl6/site/sources/E4F1DE76384365C6C75A4B00288F52887460CE7F (Bailador) line 161
  in block <unit> at status.p6 line 8
```

The problem is now in an upstream module, which I also patched: https://github.com/supernovus/perl6-fastcgi/issues/5 and this PR: https://github.com/supernovus/perl6-fastcgi/pull/7 I am not sure you are using this module, but I'm pretty sure the problem is the same, the change in interface of a core module. 

It might need to wait for a new release, or I don't know why it's propagated down to Bailador. If I find the way to patch it I will help.

**Comment by JJ** [comment] 2017-12-16 09:47
I have made a pull request to HTTP::Easy https://github.com/supernovus/perl6-http-easy/pull/38 When accepted, it should fix this problem here.

**Comment by ufobat** [comment] 2017-12-16 09:50
Awesome. Thanks for your help

**Comment by JJ** [comment] 2017-12-16 09:52
:+1:

**Comment by ufobat** [comment] 2017-12-18 19:03
PR is merged,

**Comment by JJ** [comment] 2017-12-18 19:08
I have tested Bailador with this change and it works pretty well. Give it a try :-)
